services:
  orkaris-back:
    restart: always
    container_name: orkaris-back
    build:
      context: .
      dockerfile: Dockerfile
    image: orkaris-back:1.0.0
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:5000
  postgres:
    restart: always
    container_name: orkaris-db
    image: postgres:latest
    environment:
      POSTGRES_DB: orkaris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - orkaris_data:/var/lib/postgresql/data

volumes:
  orkaris_data:
