services:
  orkaris-back:
    build:
      context: .
      dockerfile: Dockerfile
    image: orkaris-back:1.0.0
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
